[theme]
primaryColor = "#4976f5"              
backgroundColor = "#ffffff"           
secondaryBackgroundColor = "#f9f5f7"  
textColor = "#1d1d1f"                 
font = "sans serif"                  
